# Generated by Django 3.0.8 on 2020-08-31 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo_sharing', '0005_auto_20200831_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 17, 23, 5, 753196, tzinfo=utc)),
        ),
    ]
